# Generated by Django 3.1.1 on 2021-08-12 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20210812_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='cart',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='shop.cart'),
        ),
    ]
