# Generated by Django 3.1.1 on 2021-08-12 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_remove_checkout_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paytmhistory',
            name='address',
        ),
        migrations.RemoveField(
            model_name='paytmhistory',
            name='checout',
        ),
        migrations.RemoveField(
            model_name='paytmhistory',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='paytmhistory',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='paytmhistory',
            name='user',
        ),
        migrations.AlterField(
            model_name='paytmhistory',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
