# Generated by Django 3.1.1 on 2021-08-12 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0007_auto_20210812_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='paytmhistory',
            name='quantity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='paytmhistory',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paytmhistory',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
