# Generated by Django 3.1.1 on 2021-08-12 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20210812_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paytmhistory',
            name='quantity',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
