# Generated by Django 3.1.1 on 2021-08-12 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20210812_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paytmhistory',
            name='TXNID',
            field=models.CharField(max_length=3000, verbose_name='TXN ID'),
        ),
    ]
