# Generated by Django 3.1.1 on 2021-08-12 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20210812_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='product_id',
            field=models.CharField(default='', max_length=3000),
        ),
    ]
