# Generated by Django 3.1.1 on 2021-08-12 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20210812_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='quantity',
            field=models.CharField(default='', max_length=3000),
        ),
    ]
